<?php
namespace Tbx\Console;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Tk\Db;
use Tk\FileUtil;
use Tk\Log;

/**
 * @author Tropotek <info@tropotek.com>
 */
class DbRestore extends Iface
{

    protected function configure()
    {
        $this->setName('dbRestore')
            ->setAliases(['dr'])
            ->addArgument('filename', InputArgument::REQUIRED, 'The Database backup file (tgz) generated by \'tk dbBackup\'')
            ->addOption('user', 'U', InputOption::VALUE_OPTIONAL, 'The database username', 'dev')
            ->addOption('pass', 'P', InputOption::VALUE_OPTIONAL, 'The database password', 'dev007')
            ->addOption('host', 'H', InputOption::VALUE_OPTIONAL, 'The database password', 'localhost')
            ->addOption('port', 'O', InputOption::VALUE_OPTIONAL, 'The server port', 3306)
            ->addOption('type', 'M', InputOption::VALUE_OPTIONAL, 'The database type', 'mysql')
            ->addOption('dbName', 'N', InputOption::VALUE_OPTIONAL, 'The database name to import, if empty then all databases are imported', '')
            ->addOption('force', 'F')
            ->setDescription('Restore Databases backed up with the tkDbBackup command');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $filename = $input->getArgument('filename');
        if (!is_file($filename) || FileUtil::getExtension($filename) != 'tgz')
            throw new \Tk\Exception('This does not look like a valid tkDbBackup file!');

        $tempPath = sys_get_temp_dir().'/tk-dbRestore-'.getmyuid();
        $dirname = $tempPath . '/' . FileUtil::removeExtension(basename($filename));    // Path to the sql files

        if ($input->getOption('dbName'))
            $tempPath = sys_get_temp_dir().'/'.$input->getOption('dbName').'-'.getmyuid();
        if (is_dir($tempPath)) {
            FileUtil::rmdir($tempPath);
        }

        if (!is_dir($tempPath))
            mkdir($tempPath, 0777, true);

        // extract backup sql files
        $cmd = sprintf('tar zxf %s -C %s ', $filename, $tempPath);
        $this->writeComment($cmd);
        system($cmd);

        $exclude = ['Database', 'information_schema', 'performance_schema', 'phpmyadmin', 'mysql', 'dbispconfig', 'roundcube'];

        // loop through all sql files and backup if table does not exist
        foreach (new \DirectoryIterator($dirname) as $fileInfo) {
            if($fileInfo->isDot()) continue;
            $dbName = FileUtil::removeExtension($fileInfo->getFilename());

            if (in_array($dbName, $exclude)) continue;
            if (!empty($options['dbName']) && $dbName != $options['dbName']) continue;

            try {
                $this->writeComment('  Restoring ' . $dbName . ' [' . $fileInfo->getFilename() . ']:');
                $options = $input->getOptions();
                $options['dbName'] = $dbName;

                $db = Db::connect(Db::toDsn($options));

                if (Db::databaseExists($dbName)) {
                    try {
                        $db->exec('USE ' . $dbName);
                        $tables = Db::getTableList(Db::TABLES);
                        if (count($tables) > 0) {
                            if (!$input->getOption('force')) {
                                $this->writeInfo('  Skipped. (DB Exists)');
                                continue;
                            } else {
                                // delete all tables if not implementing drop tables
                                //$this->dropAllTables();
                            }
                        }
                    } catch (\Exception $e) {
                        Log::error($e->__toString());
                        $this->writeInfo('  Skipped. (DB Connection Error)');
                    }
                } else {
                    $db->exec('CREATE DATABASE IF NOT EXISTS ' . $dbName);
                    $db->exec('USE ' . $dbName);
                }
                Db\DbBackup::restore($fileInfo->getPathname(), $options);
                $this->writeComment('Restore Complete');
            } catch (\Exception $e) {
                Log::error('Error Restoring: ' . $dbName);
                Log::error($e->__toString());
                $this->writeError('Restore Failed');

                return Command::FAILURE;
            }
        }

        if (!$this->getConfig()->isDev()) {
            FileUtil::rmdir($tempPath);
        }

        $this->writeInfo('Restore complete. Remember to reload all views, events, and procedures');
        return Command::SUCCESS;
    }

    /**
     * Drop all tables, views are ignored as they are not exported via mysqldump
     */
    protected function dropAllTables($exclude = []): bool
    {
        Db::execute('SET FOREIGN_KEY_CHECKS = 0;SET UNIQUE_CHECKS = 0');
        foreach (Db::getTableList(Db::TABLES) as $table) {
            if (in_array($table, $exclude)) continue;
            Db::execute(sprintf('DROP TABLE IF EXISTS `%s` CASCADE', trim($table)));
        }
        Db::execute('SET FOREIGN_KEY_CHECKS = 1;SET UNIQUE_CHECKS = 1');
        return true;
    }

}
